---
title: "Eda assignment report"
author: "Hamze Omar"
date: "3/25/2021"
output: github_document
---


## Abstract 

## Introduction

I am Researching about Sedge Wren. Sedge Wren is a bird found in North America.
Sedge Wren is also known as Cistothorus Stellaris. It is a passerine bird in the
family of Troglodytidae mostly found in wet grasslands and meadows. 
In this project, I will focus on the Sedge Wren family on the United States soil.
I will create a graphic map or visual map that shows the characters of this bird,
such as its breeding season from time to time, where they relocate from time to time, etc.
These species are summer breeding. They habitually build their nest as early as May and continues until late August. I’ll visualize these characters on the project.


## Methods 

### Data Acquisition

First of all, I attempted to download the data, however, it was a large dataset,
which that case would take more space from my laptop, so I did not have to request
access from the original website of eBird. I went on the MSUM class share website
where the instructor uploaded it (\\msumstudents.mnstate.edu\classshare) to minimize the size of the data.Then I downloaded it. After the download, I  read the data into RStudio
(R.version). I also read into RStudio an auk package with bird observations.
I installed a cornel lab of ornithology with all the bird observations of the
dataset using the function (remote::install_girhub). I used (gridExtra) package from (Baptiste Auguie 2017), (lubridate) package from (Garrett Grolemund 2011), 
(psych) package from (Revelle, W. 2020), (readr, and dplyr) from (Hadley Wickham 2020)
.

## Results

## Discussion 

## Literature Cited

Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2021). dplyr: A
Grammar of Data Manipulation. R package version 1.0.5.
https://CRAN.R-project.org/package=dplyr
  
Garrett Grolemund, Hadley Wickham (2011). Dates and Times Made Easy with lubridate.
Journal of Statistical Software, 40(3), 1-25. URL https://www.jstatsoft.org/v40/i03/.
  
Revelle, W. (2020) psych: Procedures for Personality and Psychological Research,
  Northwestern University, Evanston, Illinois, USA,
  https://CRAN.R-project.org/package=psych Version = 2.0.12,.
  

Hadley Wickham and Jim Hester (2020). readr: Read Rectangular Text Data. R package
  version 1.4.0. https://CRAN.R-project.org/package=readr



## Websites cited

eBird Basic Dataset. Version: ebd_relFeb-2018. Cornell Lab of Ornithology, Ithaca, New York. May 2013.

https://www2.mnstate.edu/helpdesk/class-share-drive.aspx \\msumstudents.mnstate.edu\classshare
